import { save } from '@tauri-apps/plugin-dialog';
import { invoke } from '@tauri-apps/api/core';
import type { DailyPoint } from '../types';

const CELL = 11;
const GAP = 3;
const STEP = CELL + GAP;
const LEFT = 76;
const TOP = 46;
const WEEKS = 53;

const level = (n: number, max: number) => {
  if (!n) return 0;
  if (max <= 1) return 4;
  const x = n / max;
  if (x <= .2) return 1;
  if (x <= .45) return 2;
  if (x <= .72) return 3;
  return 4;
};

const colors = ['#1a1e24', '#183d2b', '#1f6b3a', '#2ea44f', '#55d976'];

function yearDays(year: number, points: Map<string, number>) {
  const jan1 = new Date(Date.UTC(year, 0, 1));
  const dec31 = new Date(Date.UTC(year, 11, 31));
  const firstSunday = new Date(jan1);
  firstSunday.setUTCDate(jan1.getUTCDate() - jan1.getUTCDay());
  const rows: Array<{ day: string; week: number; dow: number; count: number }> = [];
  for (let d = new Date(firstSunday); d <= dec31; d.setUTCDate(d.getUTCDate() + 1)) {
    if (d.getUTCFullYear() > year) break;
    const day = d.toISOString().slice(0, 10);
    if (d.getUTCFullYear() === year) {
      const diff = Math.floor((d.getTime() - firstSunday.getTime()) / 86400000);
      rows.push({ day, week: Math.floor(diff / 7), dow: d.getUTCDay(), count: points.get(day) || 0 });
    }
  }
  return rows;
}

export async function exportHeatmap(title: string, daily: DailyPoint[], startYear: number, endYear: number, format: 'png' | 'svg') {
  const map = new Map(daily.map((x) => [x.day, x.count]));
  const years = Array.from({ length: endYear - startYear + 1 }, (_, i) => startYear + i);
  const yearHeight = TOP + 7 * STEP + 34;
  const width = LEFT + WEEKS * STEP + 30;
  const height = 28 + years.length * yearHeight + 34;
  const max = Math.max(1, ...daily.map((x) => x.count));

  const esc = (s: string) => s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' }[c]!));
  let body = `<rect width="100%" height="100%" fill="#0b0e12"/><text x="24" y="30" fill="#f1f4f7" font-size="18" font-family="Segoe UI,Arial">${esc(title)}</text>`;
  years.forEach((year, yi) => {
    const oy = 28 + yi * yearHeight;
    body += `<text x="24" y="${oy + 34}" fill="#9aa4af" font-size="13" font-family="Segoe UI,Arial">${year}</text>`;
    for (const item of yearDays(year, map)) {
      const x = LEFT + item.week * STEP;
      const y = oy + TOP + item.dow * STEP;
      body += `<rect x="${x}" y="${y}" width="${CELL}" height="${CELL}" rx="2" fill="${colors[level(item.count, max)]}"/>`;
    }
  });
  body += `<text x="24" y="${height - 16}" fill="#66717d" font-size="11" font-family="Segoe UI,Arial">Generated by OJ Insight</text>`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">${body}</svg>`;
  const storage = await invoke<{ exportDir: string }>('get_storage_info');
  const slash = storage.exportDir.endsWith('\\') || storage.exportDir.endsWith('/') ? '' : '\\';
  const defaultPath = `${storage.exportDir}${slash}OJ-Insight-${startYear}-${endYear}.${format}`;
  const path = await save({ defaultPath, filters: [{ name: format.toUpperCase(), extensions: [format] }] });
  if (!path) return;
  if (format === 'svg') {
    await invoke('write_export_file', { path, data: Array.from(new TextEncoder().encode(svg)) });
    return;
  }
  const img = new Image();
  const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  try {
    await new Promise<void>((resolve, reject) => { img.onload = () => resolve(); img.onerror = reject; img.src = url; });
    const canvas = document.createElement('canvas');
    canvas.width = width * 2; canvas.height = height * 2;
    const ctx = canvas.getContext('2d')!;
    ctx.scale(2, 2); ctx.drawImage(img, 0, 0, width, height);
    const png = await new Promise<Blob>((resolve, reject) => canvas.toBlob((b) => b ? resolve(b) : reject(new Error('PNG 编码失败')), 'image/png'));
    await invoke('write_export_file', { path, data: Array.from(new Uint8Array(await png.arrayBuffer())) });
  } finally { URL.revokeObjectURL(url); }
}
