import { createContext, useContext, type ReactNode } from 'react';

export type LanguagePreference = 'system' | 'zh-CN' | 'en-US';
export type Locale = 'zh-CN' | 'en-US';

export function resolveLocale(preference: LanguagePreference): Locale {
  if (preference !== 'system') return preference;
  const language = typeof navigator === 'undefined' ? 'zh-CN' : navigator.language;
  return language.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en-US';
}

export function currentLocale(): Locale {
  try {
    const saved = localStorage.getItem('oj-insight.preferences');
    if (!saved) return resolveLocale('system');
    const preference = (JSON.parse(saved) as { language?: LanguagePreference }).language;
    return resolveLocale(preference === 'system' || preference === 'en-US' || preference === 'zh-CN' ? preference : 'zh-CN');
  } catch {
    return 'zh-CN';
  }
}

const english: Record<string, string> = {
  '总览': 'Overview', '训练中心': 'Training Center', '题单': 'Problem Sets', '推荐题单': 'Community Sets',
  '模拟赛': 'Mock Contests', '参赛区': 'Virtual Contests', '个性化组题': 'Personalized Training',
  '解题手记': 'Solve Journal', '做题小助手': 'Study Assistant', '赛后分析': 'Contest Review',
  '关注': 'Following', '导出': 'Export', '数据源': 'Data Sources', '设置': 'Settings', '关于': 'About',
  '展开侧栏': 'Expand sidebar', '收起侧栏': 'Collapse sidebar',
  '管理平台账号和本机显示偏好。': 'Manage your platform accounts and display preferences.',
  '保存中': 'Saving', '保存账号': 'Save Accounts', '账号设置': 'Accounts', '个性化': 'Preferences',
  '怎么填写？': 'How to fill this in?',
  '填写个人主页 URL 中的账号标识，不是显示昵称。Cookie 与 API 凭据仅保存在本机；获取入口位于对应 OJ 页的同步按钮左侧。删除或改名会在保存时清理原 ID 的本地记录。': 'Enter the account ID from your profile URL, not your display name. Cookies and API credentials stay on this device. Find credential settings beside the sync button on each OJ page. Removing or renaming an ID clears its local records when you save.',
  '添加 ID': 'Add ID', '移除账号': 'Remove account', '公开数据，无需密码': 'Public data; no password needed',
  '外观': 'Appearance', '修改后立即生效，并保存在当前设备。': 'Changes take effect immediately and are saved on this device.',
  '主题': 'Theme', '灰色介于亮色与暗色之间；跟随系统仍响应操作系统的亮暗模式。': 'Gray sits between light and dark. System follows your OS appearance.',
  '跟随系统': 'System', '亮色': 'Light', '灰色': 'Gray', '暗色': 'Dark',
  '字号': 'Font size', '标准字号已经提高小字尺寸，不会恢复到原来的过小字号。': 'Standard already uses larger small text.',
  '标准': 'Standard', '放大': 'Large', '特大': 'Extra large',
  '界面密度': 'Interface density', '只调整卡片和列表间距，不缩小文字。': 'Adjust card and list spacing without shrinking text.',
  '舒适': 'Comfortable', '紧凑': 'Compact', '图表与动效': 'Charts and motion',
  '改善长时间查看统计数据时的辨识度。': 'Make statistics easier to read for longer sessions.',
  '活动砖配色': 'Activity colors', '只影响训练热力图，不覆盖各 OJ 的平台颜色。': 'Affects only the activity heatmap, not OJ platform colors.',
  '绿色': 'Green', '蓝色': 'Blue', '色觉友好': 'Color accessible',
  '减少动态效果': 'Reduce motion', '关闭曲线、活动砖和页面状态的过渡动画。': 'Disable chart, heatmap and page transitions.',
  '常规': 'General', '统计范围与统计口径仍在总览和各 OJ 页面中切换。': 'Choose ranges and metrics on Overview and each OJ page.',
  '统计时区': 'Statistics time zone', '影响今日进度、活动砖、连续天数和问候语。': 'Affects today’s progress, activity heatmaps, streaks and greetings.',
  '启动页面': 'Startup page', '固定打开总览，或回到上次浏览的位置。': 'Open Overview or return to your last page.',
  '上次浏览': 'Last viewed', '最近 AC 通知保留条数': 'Recent AC notifications to keep',
  '历史通知单独保存；超过上限时自动删除较旧记录，最多 100 条。': 'Older notifications are stored separately. Keep up to 100 recent items.',
  '条': 'items', '启动时检查更新': 'Check for updates at startup',
  '后台检查新版本；没有更新或临时断网时不打扰。': 'Check in the background without interrupting you when nothing is available.',
  '启动时同步全部': 'Sync all at startup', '先显示本地缓存，再在后台增量同步已配置的平台。': 'Show cached data first, then sync configured platforms in the background.',
  '恢复个性化默认值': 'Reset preferences', '界面语言': 'Interface language',
  '选择应用界面使用的语言；题目名称、OJ 标签和你的笔记不会翻译。': 'Choose the app language. Problem titles, OJ tags and your notes stay in their original language.',
  '简体中文': '简体中文', 'English': 'English',
  '开发中': 'In development',
  '中国标准时间 · UTC+8': 'China Standard Time · UTC+8', '东京 · UTC+9': 'Tokyo · UTC+9',
  '新加坡 · UTC+8': 'Singapore · UTC+8', '香港 · UTC+8': 'Hong Kong · UTC+8',
  '印度 · UTC+5:30': 'India · UTC+5:30', '伦敦': 'London', '巴黎': 'Paris',
  '纽约': 'New York', '芝加哥': 'Chicago', '丹佛': 'Denver', '洛杉矶': 'Los Angeles',
  '悉尼': 'Sydney', '协调世界时 · UTC': 'Coordinated Universal Time · UTC',
  '至少选择一个平台': 'Select at least one platform',
  '候选池：{count} 道；排除已做 {excluded} 道': 'Candidate pool: {count}; excluded solved: {excluded}',
  '组题包已保存到 {path}': 'Training pack saved to {path}',
  '请选择 OJ Insight 生成的 JSON 文件': 'Choose a JSON file generated by OJ Insight',
  '比赛“{title}”已导入': 'Contest “{title}” imported', '题单“{title}”已导入': 'Problem set “{title}” imported',
  '先由 OJ Insight 从可靠目录初筛，再让大模型在候选池中复筛和编排。上传一个 ZIP 即可，无需额外提示词。': 'OJ Insight first selects from reliable catalogs, then an AI model refines and arranges the candidate pool. Upload one ZIP file; no extra prompt is needed.',
  '导入大模型生成的 JSON 文件并保存为比赛': 'Import AI-generated JSON as a contest',
  '导入大模型生成的 JSON 文件并保存为题单': 'Import AI-generated JSON as a problem set',
  '导入为比赛': 'Import as Contest', '导入为题单': 'Import as Problem Set',
  '生成候选池': 'Generate Candidate Pool', '训练模式是节奏与压力目标；完成比例为可调建议。': 'Training modes set pace and pressure; solve rates are adjustable targets.',
  '轻松': 'Relaxed', '均衡': 'Balanced', '压力': 'Pressure',
  '稳定输出，保持题感': 'Build consistency and stay sharp',
  '正常训练，兼顾强项与上限': 'Balance strengths with growth',
  '时间与选题压力，加入陌生性': 'Add time pressure and unfamiliar problems',
  '参考比例 {target}': 'Target solve rate {target}',
  '初筛平台': 'Candidate platforms', '洛谷、牛客和 LeetCode 暂无足够可靠的完整目录。': 'Luogu, NowCoder and LeetCode do not yet have sufficiently reliable full catalogs.',
  '候选池大小': 'Candidate pool size', '正在筛题…': 'Selecting problems…',
  '候选池已准备好': 'Candidate pool ready',
  '{count} 道可用题 · 排除已做 {excluded} 道': '{count} available problems · {excluded} solved problems excluded',
  '{count} 道目录题': '{count} catalog problems', '查看候选题': 'View candidates',
  '额外组题要求（可选）': 'Extra instructions (optional)', '留空即可直接把 ZIP 交给大模型': 'Leave empty to send the ZIP directly to an AI model',
  '导出组题包 ZIP': 'Export Training Pack ZIP',
  '模型返回一个 JSON；选择导入为比赛或可复用题单。': 'The model returns a JSON file. Import it as a contest or reusable problem set.',
  '最近导出': 'Last export', '打开所在文件夹': 'Open containing folder',
  '读取失败：{error}': 'Could not load: {error}', '已切换到所选草稿': 'Switched to selected draft',
  '切换草稿失败：{error}': 'Could not switch drafts: {error}', '保存失败：{error}': 'Could not save: {error}',
  '重新开始计时会将本次用时清零，继续吗？': 'Restarting the timer will clear the elapsed time. Continue?',
  '关闭前保存失败：{error}': 'Could not save before closing: {error}',
  '请先填写题目、记录笔记或开始计时': 'Enter a problem, write a note, or start the timer first',
  '已保存到训练中心 · 解题手记': 'Saved to Training Center · Solve Journal',
  '归档失败：{error}': 'Could not finish this attempt: {error}',
  '调整小助手窗口大小：{direction}': 'Resize Study Assistant: {direction}',
  '收起小助手': 'Collapse Study Assistant', '关闭小助手': 'Close Study Assistant',
  '题目名称': 'Problem title', '题目名称（可稍后填写）': 'Problem title (optional for now)',
  '题目链接': 'Problem URL', '题目链接（可选）': 'Problem URL (optional)', '题目平台': 'Problem platform',
  '未指定平台': 'No platform selected', '已用时间': 'Elapsed time',
  '计时中': 'Running', '已停止': 'Stopped', '已暂停': 'Paused', '准备开始': 'Ready',
  '暂停': 'Pause', '重新开始': 'Restart', '继续': 'Resume', '开始': 'Start', '停止': 'Stop',
  '重置本次计时？笔记和失误记录会保留。': 'Reset the timer? Notes and mistakes will be kept.',
  '重置': 'Reset', '失误原因': 'Mistake reason',
  '失误备注': 'Mistake note', '备注（可选）': 'Note (optional)',
  '+ 记一次失误': '+ Record mistake', '已记 {count} 次': '{count} mistakes recorded',
  '粗心': 'Carelessness', '思路偏差': 'Wrong approach', '实现错误': 'Implementation error',
  '知识盲点': 'Knowledge gap', '时间分配': 'Time management', '其他': 'Other',
  '完成情况': 'Outcome', '已完成': 'Solved', '未完成 / 待复习': 'Unfinished / Review later',
  '结束本次做题': 'Finish attempt', 'Markdown 笔记': 'Markdown notes',
  '自动保存草稿 · 输入 # 补全标签': 'Draft autosaved · Type # for tag suggestions',
  '编辑': 'Edit', '预览': 'Preview', '小助手 Markdown 笔记': 'Study Assistant Markdown notes',
  '记录思路、样例和待验证的想法。支持 Markdown、$行内公式$ 与 $$独立公式$$。': 'Record ideas, samples and things to verify. Supports Markdown and LaTeX math.',
  '暂无笔记': 'No notes yet', '小助手': 'Assistant',
  '展开做题小助手，已计时 {elapsed}': 'Expand Study Assistant, elapsed {elapsed}',
  '{minutes} 分钟': '{minutes} min', '读取解题手记失败：{error}': 'Could not load Solve Journal: {error}',
  '读取 Competitive Companion 状态失败：{error}': 'Could not read Competitive Companion status: {error}',
  '端口须为 1024–65535 的整数': 'Port must be an integer from 1024 to 65535',
  'Competitive Companion 接收端已监听 {port}': 'Competitive Companion receiver is listening on {port}',
  '设置接收端口失败：{error}': 'Could not set receiver port: {error}',
  '未命名练习': 'Untitled attempt', '手记已保存': 'Journal entry saved',
  '删除“{title}”这次记录？此操作无法撤销。': 'Delete “{title}”? This cannot be undone.',
  '记录已删除': 'Entry deleted', '删除失败：{error}': 'Could not delete: {error}',
  '已导出到 {path}': 'Exported to {path}', '导出失败：{error}': 'Could not export: {error}',
  '请选择 OJ Insight 解题手记 JSON': 'Choose an OJ Insight Solve Journal JSON file',
  '文件包含无效记录': 'The file contains invalid entries',
  '已导入 {count} 条；同 ID 的现有记录已保留': 'Imported {count} entries; existing IDs were kept',
  '导入失败：{error}': 'Could not import: {error}',
  '保存每次练习的用时、思路、标签和失误，随时回看与复盘。': 'Keep time, ideas, tags and mistakes from each attempt for later review.',
  '导出 JSON': 'Export JSON', '导出 CSV': 'Export CSV', '失误明细 CSV': 'Mistakes CSV',
  '导入 JSON': 'Import JSON', '开始一次练习': 'Start an attempt',
  '打开悬浮小助手，边做题边计时和记笔记；结束后自动收录到这里。关闭窗口会保留草稿。': 'Open the floating assistant to time your work and take notes. Finished attempts appear here; closing the window keeps your draft.',
  '打开做题小助手': 'Open Study Assistant', '浏览器一键收题': 'Send a problem from your browser',
  '在扩展设置的 Custom Ports 中添加 OJI 端口。点击扩展后，运行中的 OJI 会自动建立草稿；计时仍由你手动开始。CPH 可同时接收。': 'Add the OJI port under Custom Ports in Competitive Companion. Clicking the extension creates a draft while OJI is running. Start the timer yourself; CPH can receive the same problem.',
  'OJI 端口': 'OJI port', 'Competitive Companion 端口': 'Competitive Companion port',
  '设置中…': 'Applying…', '应用端口': 'Apply port', '重试监听': 'Retry listener',
  '正在监听 127.0.0.1:{port}': 'Listening on 127.0.0.1:{port}',
  '检查监听状态…': 'Checking listener…', '桌面应用安装版可用': 'Available in the installed desktop app',
  '搜索解题手记': 'Search Solve Journal', '搜索题目、标签、笔记': 'Search problems, tags, notes',
  '筛选记录': 'Filter entries', '全部记录': 'All entries', '草稿': 'Draft', '已结束': 'Finished',
  '筛选平台': 'Filter platform', '全部平台': 'All platforms', '筛选日期': 'Filter date',
  '共 {count} 条记录': '{count} entries', '待复习': 'Review later',
  '暂无匹配的记录': 'No matching entries', '未结束草稿': 'Unfinished draft',
  '已归档记录': 'Archived entry', '继续草稿': 'Resume draft', '取消编辑': 'Cancel editing',
  '删除记录': 'Delete entry', '编辑题目名称': 'Edit problem title', '编辑手记': 'Edit journal entry',
  '保存中…': 'Saving…', '保存修改': 'Save changes', '来源：{group}': 'Source: {group}',
  '开始：{date}': 'Started: {date}', '结束：{date}': 'Ended: {date}',
  '用时：{duration}': 'Time: {duration}', '失误：{count} 次': 'Mistakes: {count}',
  '打开原题': 'Open problem', '做题笔记': 'Problem notes', '失误记录': 'Mistakes',
  '暂无失误记录': 'No mistakes recorded',
  '计时 {elapsed}': 'Timer {elapsed}',
  '选择一条记录查看详情': 'Select an entry to view details',
  '用户名': 'Username', '用户名或数字 UID': 'Username or numeric UID',
  '个人主页 users/ 后的数字 User ID': 'Numeric user ID after users/ in your profile URL',
  '国际站用户名；中国站写 cn:用户名': 'Global username; use cn:username for China',
  '可选：Codeforces API Key / Secret': 'Optional: Codeforces API Key / Secret',
  '可选：牛客网页 Cookie（用于同步每日一题打卡记录）': 'Optional: NowCoder cookie for daily challenge history',
  '完整 Cookie（名称=值，可粘贴多项）': 'Full cookie (name=value; multiple entries supported)',
  '可选：对应站点 Cookie（中国站活动与最近 AC 兜底）': 'Optional: site cookie for China activity and recent AC fallback',
  'API Key（可选）': 'API Key (optional)', 'API Secret（可选）': 'API Secret (optional)',
  '从未': 'Never',
  '{platform} 中存在重复 ID，请合并后保存': 'Duplicate IDs in {platform}. Merge them before saving.',
  '将移除以下 ID 及其本地提交、活动、难度、Rating 和同步记录：\n{ids}\n\n其他 ID 的记录会保留。确认保存？': 'The following IDs and their local submissions, activity, difficulty, rating and sync records will be removed:\n{ids}\n\nRecords for other IDs will be kept. Save these changes?',
}; 

const LocaleContext = createContext<Locale>('zh-CN');

export function LocaleProvider({ locale, children }: { locale: Locale; children: ReactNode }) {
  return <LocaleContext.Provider value={locale}>{children}</LocaleContext.Provider>;
}

export function translate(locale: Locale, key: string, values?: Record<string, string | number>): string {
  const template = locale === 'en-US' ? english[key] || key : key;
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values?.[name] ?? `{${name}}`));
}

export function useI18n() {
  const locale = useContext(LocaleContext);
  return { locale, t: (key: string, values?: Record<string, string | number>) => translate(locale, key, values) };
}
