export type Page =
  | 'overview'
  | 'xcpc'
  | 'tracker-codeforces'
  | 'tracker-atcoder'
  | 'contest-review'
  | 'problem-sets'
  | 'community'
  | 'favorites'
  | 'contests'
  | 'vp'
  | 'training'
  | 'solve-journal'
  | 'relationships'
  | 'export'
  | 'data'
  | 'settings'
  | 'about';
