import { useRef, useState } from 'react';
import { Download, FileUp, Plus, Save, Trash2 } from 'lucide-react';
import { PLATFORM_META, PLATFORM_ORDER } from '../lib/platforms';
import { useTraining } from '../hooks/useTraining';
import { api } from '../services/api';
import { saveTrainingJson } from '../services/training';
import type { ProblemSet, ProblemSetInput, ProblemSetProblem, TrainingRole } from '../types';

const ROLES: TrainingRole[] = ['Warmup', 'Stable', 'Core', 'Weakness', 'Observation', 'Stretch'];
const emptyProblem = (): ProblemSetProblem => ({ position: 0, role: 'Core', note: '', problem: { canonicalId: '', platform: 'codeforces', problemKey: '', problemId: '', name: '', url: '', difficulty: null, tags: [], trainingSuitability: null, observationDependency: null, implementationLoad: null, knowledgeDependency: null, interactive: false, outputOnly: false } });
const emptyDraft = (): ProblemSetInput => ({ id: null, title: '', description: '', setType: 'static', tagVisibility: 'after_ac', sourceSetId: null, sourceUrl: null, problems: [emptyProblem()] });

export default function ProblemSetsPage({ notify }: { notify: (message: string) => void }) {
  const { sets, loading, saveSet, deleteSet, importSet } = useTraining(notify);
  const [draft, setDraft] = useState<ProblemSetInput>(emptyDraft);
  const inputRef = useRef<HTMLInputElement>(null);
  const edit = (set: ProblemSet) => setDraft({ id: set.id, title: set.title, description: set.description, setType: 'static', tagVisibility: set.tagVisibility, sourceSetId: set.sourceSetId, sourceUrl: set.sourceUrl, problems: set.problems });
  const updateProblem = (index: number, patch: Omit<Partial<ProblemSetProblem>, 'problem'> & { problem?: Partial<ProblemSetProblem['problem']> }) => setDraft((current) => ({ ...current, problems: current.problems.map((entry, position) => position === index ? { ...entry, ...patch, problem: { ...entry.problem, ...(patch.problem || {}) } } : entry) }));
  const submit = async () => { try { await saveSet({ ...draft, problems: draft.problems.map((entry, position) => ({ ...entry, position })) }); setDraft(emptyDraft()); notify('题单已保存'); } catch (error) { notify(String(error)); } };
  const onImport = async (file?: File) => { if (!file) return; try { await importSet(await file.text()); notify('题单已导入'); } catch (error) { notify(String(error)); } finally { if (inputRef.current) inputRef.current.value = ''; } };
  const exportSet = async (set: ProblemSet) => { try { const data = await api.exportProblemSet(set.id); if (await saveTrainingJson(`OJ-Insight-problem-set-${set.id}.json`, data)) notify('题单已导出'); } catch (error) { notify(String(error)); } };
  return <>
    <header className="topbar"><div><small>PROBLEM SETS</small><h1>跨 OJ 题单</h1><p>创建、排序和分享静态题单。题目标识使用平台与 problem key 组合，可直接启动训练赛。</p></div><div className="topbar-actions"><input ref={inputRef} hidden type="file" accept="application/json,.json" onChange={(event) => void onImport(event.target.files?.[0])} /><button onClick={() => inputRef.current?.click()}><FileUp size={15} />导入 JSON</button><button className="primary" onClick={() => setDraft(emptyDraft())}><Plus size={15} />新建题单</button></div></header>
    <div className="training-grid">
      <section className="panel problem-set-list"><header><strong>本地题单</strong><small>{loading ? '读取中…' : `${sets.length} 个`}</small></header>{sets.length ? sets.map((set) => <article key={set.id} className={draft.id === set.id ? 'active' : ''}><button className="set-main" onClick={() => edit(set)}><strong>{set.title}</strong><span>{set.problems.length} 题 · 标签 {set.tagVisibility === 'after_ac' ? 'AC 后显示' : set.tagVisibility === 'never' ? '从不显示' : '解题前显示'}</span></button><button title="导出" onClick={() => void exportSet(set)}><Download size={14} /></button><button title="删除" onClick={() => { if (confirm(`删除题单“${set.title}”？`)) void deleteSet(set.id).catch((error) => notify(String(error))); }}><Trash2 size={14} /></button></article>) : <p className="training-empty">还没有题单。可以手动创建或导入 Manifest。</p>}</section>
      <section className="panel set-editor"><header><div><small>{draft.id ? `SET #${draft.id}` : 'NEW STATIC SET'}</small><h2>{draft.id ? '编辑题单' : '创建题单'}</h2></div><button className="primary" onClick={() => void submit()}><Save size={15} />保存</button></header>
        <div className="set-fields"><label><span>题单名称</span><input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="例如：图论基础训练" /></label><label><span>标签可见性</span><select value={draft.tagVisibility} onChange={(event) => setDraft({ ...draft, tagVisibility: event.target.value as ProblemSetInput['tagVisibility'] })}><option value="after_ac">AC 后显示</option><option value="before_solving">解题前显示</option><option value="never">从不显示</option></select></label><label className="wide"><span>说明</span><textarea value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label></div>
        <div className="problem-editor"><header><strong>题目</strong><button onClick={() => setDraft({ ...draft, problems: [...draft.problems, { ...emptyProblem(), position: draft.problems.length }] })}><Plus size={14} />添加题目</button></header>{draft.problems.map((entry, index) => <article key={index}><b>{index + 1}</b><select value={entry.problem.platform} onChange={(event) => updateProblem(index, { problem: { platform: event.target.value as ProblemSetProblem['problem']['platform'] } })}>{PLATFORM_ORDER.map((platform) => <option key={platform} value={platform}>{PLATFORM_META[platform].name}</option>)}</select><input value={entry.problem.problemKey} onChange={(event) => updateProblem(index, { problem: { problemKey: event.target.value } })} placeholder="problem key" /><input value={entry.problem.name} onChange={(event) => updateProblem(index, { problem: { name: event.target.value } })} placeholder="题目名称" /><input value={entry.problem.url} onChange={(event) => updateProblem(index, { problem: { url: event.target.value } })} placeholder="题目链接" /><select value={entry.role} onChange={(event) => updateProblem(index, { role: event.target.value as TrainingRole })}>{ROLES.map((role) => <option key={role}>{role}</option>)}</select><input value={entry.note} onChange={(event) => updateProblem(index, { note: event.target.value })} placeholder="备注" /><input value={entry.problem.tags.join(', ')} onChange={(event) => updateProblem(index, { problem: { tags: event.target.value.split(',').map((tag) => tag.trim()).filter(Boolean) } })} placeholder="标签（逗号分隔）" /><div className="problem-order"><button disabled={index === 0} onClick={() => setDraft((current) => { const problems = [...current.problems]; [problems[index - 1], problems[index]] = [problems[index], problems[index - 1]]; return { ...current, problems }; })}>↑</button><button disabled={index === draft.problems.length - 1} onClick={() => setDraft((current) => { const problems = [...current.problems]; [problems[index + 1], problems[index]] = [problems[index], problems[index + 1]]; return { ...current, problems }; })}>↓</button><button onClick={() => setDraft({ ...draft, problems: draft.problems.filter((_, position) => position !== index) })}><Trash2 size={13} /></button></div></article>)}</div>
      </section>
    </div>
  </>;
}
