import { useEffect, useRef, useState } from 'react';
import { CheckCircle2, ChevronDown, Download, ExternalLink, FileUp, Flag, FolderOpen, Play, RefreshCw, Sparkles, Timer, Trash2 } from 'lucide-react';

import PlatformIcon from '../components/PlatformIcon';
import { useTraining } from '../hooks/useTraining';
import { PLATFORM_META } from '../lib/platforms';
import { api } from '../services/api';
import { openTrainingExportDirectory, saveTrainingFile, saveTrainingJson } from '../services/training';
import type { CandidatePool, Platform, TrainingMatch, TrainingMode } from '../types';

const MODES: Array<{ id: TrainingMode; name: string; target: [number, number]; description: string }> = [
  { id: 'relaxed', name: '轻松', target: [70, 90], description: '稳定输出，保持题感和熟练度' },
  { id: 'balanced', name: '均衡', target: [50, 70], description: '兼顾稳定题、训练目标和上限题' },
  { id: 'pressure', name: '压力', target: [35, 55], description: '加入时间、选题与一定陌生性压力' },
];
const AUTO_PLATFORMS: Platform[] = ['codeforces', 'atcoder', 'qoj'];

function MatchCard({ item, onRefresh, onFinish, onExport, onDelete }: { item: TrainingMatch; onRefresh: () => void; onFinish: () => void; onExport: () => void; onDelete: () => void }) {
  const [now, setNow] = useState(Date.now());
  const [expanded, setExpanded] = useState(item.status === 'running');
  useEffect(() => { if (item.status !== 'running') return; const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, [item.status]);
  const remaining = Math.max(0, Math.floor((item.startedAt * 1000 + item.durationMinutes * 60_000 - now) / 1000));
  const solved = item.problems.filter((problem) => problem.solved).length;
  return <article className={`training-match ${item.status}`}><header><button className="match-title" onClick={() => setExpanded((value) => !value)}><ChevronDown className={expanded ? 'expanded' : ''} size={16} /><div><small>{item.mode === 'relaxed' ? '轻松' : item.mode === 'balanced' ? '均衡' : '压力'} · {item.status === 'running' ? '进行中' : '已结束'}</small><h2>{item.title}</h2></div></button><span><Timer size={14} />{item.status === 'running' ? `${Math.floor(remaining / 60)}:${String(remaining % 60).padStart(2, '0')}` : '已完成'}</span></header><div className="match-progress"><strong>{solved}/{item.problems.length}</strong><span>目标 {Math.round(item.targetSolveRateMin * 100)}%–{Math.round(item.targetSolveRateMax * 100)}%</span><i><b style={{ width: `${item.problems.length ? solved / item.problems.length * 100 : 0}%` }} /></i></div>{expanded && <><div className="match-problems">{item.problems.map((entry) => { const showTags = item.tagVisibility === 'before_solving' || (item.tagVisibility === 'after_ac' && entry.solved); return <a key={entry.problem.canonicalId} className={entry.solved ? 'solved' : ''} href={entry.problem.url || undefined} target="_blank" rel="noreferrer"><PlatformIcon platform={entry.problem.platform} /><span>{entry.position + 1}</span><div><strong>{entry.problem.name || entry.problem.problemId || entry.problem.problemKey}</strong><small>{PLATFORM_META[entry.problem.platform].name} · {entry.role}{entry.note ? ` · ${entry.note}` : ''}</small>{showTags && entry.problem.tags.length > 0 && <em>{entry.problem.tags.join(' · ')}</em>}</div>{entry.solved ? <CheckCircle2 size={17} /> : <ExternalLink size={14} />}</a>; })}</div><footer><button onClick={onRefresh}><RefreshCw size={14} />检查同步结果</button><button onClick={onExport}><Download size={14} />导出复盘数据</button>{item.status === 'running' && <button className="primary" onClick={onFinish}><Flag size={14} />结束训练</button>}<button className="danger-ghost" onClick={onDelete}><Trash2 size={14} />删除记录</button></footer></>}</article>;
}

export default function TrainingPage({ notify, onOpenProblemSets }: { notify: (message: string) => void; onOpenProblemSets: () => void }) {
  const { sets, matches, loading, startMatch, importSet, refreshMatch, finishMatch, deleteMatch } = useTraining(notify);
  const preferredSet = Number(localStorage.getItem('oj-insight.training-set-id')) || null;
  const [setId, setSetId] = useState<number | null>(preferredSet);
  const [mode, setMode] = useState<TrainingMode>('balanced');
  const [duration, setDuration] = useState(120);
  const [target, setTarget] = useState<[number, number]>([50, 70]);
  const [platforms, setPlatforms] = useState<Platform[]>(AUTO_PLATFORMS);
  const [candidateCount, setCandidateCount] = useState(36);
  const [pool, setPool] = useState<CandidatePool | null>(null);
  const [generating, setGenerating] = useState(false);
  const [savedPath, setSavedPath] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);
  useEffect(() => { if (setId == null && sets[0]) setSetId(sets[0].id); }, [sets, setId]);

  const chooseMode = (next: TrainingMode) => { setMode(next); setTarget(MODES.find((entry) => entry.id === next)?.target || [50, 70]); setPool(null); };
  const generate = async () => { if (!platforms.length) return notify('至少选择一个候选题平台'); setGenerating(true); try { const result = await api.generateTrainingCandidates(platforms, mode, candidateCount); setPool(result); notify(`候选池已生成：${result.candidates.length} 道题，排除已做 ${result.excludedSolved} 道`); } catch (error) { notify(String(error)); } finally { setGenerating(false); } };
  const exportPack = async () => { if (!pool) return; try { const bytes = await api.exportAiTrainingPack(pool.candidates, mode); const saved = await saveTrainingFile(`OJ-Insight-AI组题包-${Date.now()}.zip`, bytes, 'zip'); if (saved) { setSavedPath(saved.path); notify(`AI 组题包已保存到 ${saved.path}`); } } catch (error) { notify(String(error)); } };
  const importGeneratedSet = async (file?: File) => { if (!file) return; try { const set = await importSet(await file.text()); localStorage.setItem('oj-insight.training-set-id', String(set.id)); setSetId(set.id); notify(`AI 生成题单“${set.title}”已导入，请先查看再开始训练`); onOpenProblemSets(); } catch (error) { notify(String(error)); } finally { if (fileRef.current) fileRef.current.value = ''; } };
  const start = async () => { if (setId == null) return notify('请先选择一个已有题单'); try { await startMatch(setId, mode, duration, target[0] / 100, target[1] / 100); localStorage.removeItem('oj-insight.training-set-id'); notify('训练赛已开始，已做题已自动排除'); } catch (error) { notify(String(error)); } };
  const removeMatch = async (item: TrainingMatch) => { if (!confirm(`删除训练记录“${item.title}”？题单和 OJ 同步数据会保留。`)) return; try { await deleteMatch(item.id); notify('训练记录已删除'); } catch (error) { notify(String(error)); } };
  const exportReview = async (item: TrainingMatch) => { const saved = await saveTrainingJson(`OJ-Insight-训练复盘-${item.id}.json`, `${JSON.stringify({ schema: 'com.ojinsight.training-review', schemaVersion: 1, exportedAt: new Date().toISOString(), match: item }, null, 2)}\n`); if (saved) { setSavedPath(saved.path); notify(`训练复盘数据已保存到 ${saved.path}`); } };

  return <>
    <header className="topbar"><div><small>TRAINING CENTER</small><h1>个性化训练</h1><p>OJ Insight 从可靠题目目录和本地训练数据生成候选池，再由大模型在候选范围内编排题单。</p></div></header>
    <section className="panel training-builder"><header className="training-section-title"><div><small>PERSONALIZED TRAINING</small><h2>创建个性化训练</h2><p>训练模式描述节奏和压力，不是简单的低、中、高难度。</p></div><Sparkles size={22} /></header><div className="training-modes">{MODES.map((entry) => <button key={entry.id} className={mode === entry.id ? 'active' : ''} onClick={() => chooseMode(entry.id)}><strong>{entry.name}</strong><span>{entry.description}</span><small>目标完成比例 {entry.target[0]}%–{entry.target[1]}% · 可调整</small></button>)}</div><div className="candidate-controls"><div><span>参与自动筛题的平台</span><div className="platform-picks">{AUTO_PLATFORMS.map((platform) => <button key={platform} className={platforms.includes(platform) ? 'active' : ''} onClick={() => { setPlatforms((current) => current.includes(platform) ? current.filter((item) => item !== platform) : [...current, platform]); setPool(null); }}><PlatformIcon platform={platform} />{PLATFORM_META[platform].name}</button>)}</div><small>洛谷、牛客和 LeetCode 暂无足够可靠的完整目录，因此不会假装参与自动筛题。</small></div><label><span>候选池大小</span><input type="number" min={12} max={120} value={candidateCount} onChange={(event) => { setCandidateCount(Number(event.target.value)); setPool(null); }} /></label><button className="primary generate-candidates" disabled={generating} onClick={() => void generate()}><Sparkles size={16} />{generating ? '正在读取可靠目录…' : '生成候选池'}</button></div>{pool && <div className="candidate-result"><header><div><strong>候选池已准备好</strong><span>{pool.candidates.length} 道可用题 · 已排除做过的 {pool.excludedSolved} 道</span></div><button className="primary" onClick={() => void exportPack()}><Download size={15} />导出 AI 组题包</button></header><div className="source-statuses">{pool.sources.map((source) => <span key={source.platform} className={source.available ? 'ok' : 'unavailable'}><i />{PLATFORM_META[source.platform].name} · {source.available ? `${source.problemCount} 道目录题` : source.message}</span>)}</div><details><summary>查看候选题</summary><div className="candidate-preview">{pool.candidates.slice(0, 30).map((problem) => <a key={problem.canonicalId} href={problem.url} target="_blank" rel="noreferrer"><PlatformIcon platform={problem.platform} /><span><strong>{problem.name}</strong><small>{problem.problemId}{problem.difficulty ? ` · ${problem.difficulty}` : ''}</small></span><ExternalLink size={13} /></a>)}</div></details><div className="ai-flow"><span><b>1</b>把 ZIP 交给大模型</span><i>→</i><span><b>2</b>模型返回题单 JSON</span><i>→</i><button onClick={() => fileRef.current?.click()}><FileUp size={14} />导入 AI 生成题单</button><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={(event) => void importGeneratedSet(event.target.files?.[0])} /></div>{savedPath && <div className="export-result"><span><strong>最近导出</strong>{savedPath}</span><button onClick={() => void openTrainingExportDirectory(savedPath)}><FolderOpen size={14} />打开所在文件夹</button></div>}</div>}</section>
    <section className="panel direct-training"><header className="training-section-title"><div><small>DIRECT MATCH</small><h2>从已有题单直接训练</h2><p>这是自定义题单的独立入口，不参与上面的自动候选筛选。</p></div></header><div className="training-start"><label><span>选择题单</span><select value={setId || ''} onChange={(event) => setSetId(Number(event.target.value))}><option value="" disabled>选择题单</option>{sets.map((set) => <option key={set.id} value={set.id}>{set.title} · {set.problems.length} 题</option>)}</select></label><label><span>时长（分钟）</span><input type="number" min={15} max={480} value={duration} onChange={(event) => setDuration(Number(event.target.value))} /></label><label><span>目标完成比例</span><div className="target-rate"><input type="number" min={0} max={100} value={target[0]} onChange={(event) => setTarget([Number(event.target.value), target[1]])} /><b>–</b><input type="number" min={0} max={100} value={target[1]} onChange={(event) => setTarget([target[0], Number(event.target.value)])} /></div></label><button className="primary" disabled={loading || setId == null} onClick={() => void start()}><Play size={16} />开始训练</button></div></section>
    <section className="training-match-list"><header><div><strong>训练与复盘</strong><small>{matches.length} 场 · 可展开查看、同步、导出复盘或删除</small></div></header>{matches.length ? matches.map((item) => <MatchCard key={item.id} item={item} onRefresh={() => void refreshMatch(item.id).then(() => notify('已根据本地同步记录更新')).catch((error) => notify(String(error)))} onFinish={() => void finishMatch(item.id).then(() => notify('训练赛已结束')).catch((error) => notify(String(error)))} onExport={() => void exportReview(item).catch((error) => notify(String(error)))} onDelete={() => void removeMatch(item)} />) : <div className="panel training-empty">还没有训练记录。可以自动生成候选池，也可以从已有题单直接开始。</div>}</section>
  </>;
}
