use std::io::{Cursor, Write};

use super::{CanonicalProblem, TrainingPack, TrainingPackFile};

pub(crate) fn build_training_pack(candidates: &[CanonicalProblem], mode: &str, profile: String) -> Result<TrainingPack, String> {
    let (min, max) = super::template::target_solve_rate(mode)?;
    let intent = super::template::mode_intent(mode)?;
    let candidates_json = serde_json::to_string_pretty(candidates).map_err(|e| e.to_string())?;
    let constraints = format!("# Constraints\n\n- Mode: {mode}\n- Mode intent: {intent}\n- Target solve rate: {:.0}%–{:.0}% (adjustable, to be validated)\n- The mode describes training pressure and composition, not a simple low/medium/high difficulty switch.\n- Use only CANDIDATES.json. Never search for or invent another problem.\n- Copy each selected `problem` object completely from CANDIDATES.json; do not rewrite its identity, name, URL, or metadata.\n- The candidates have already excluded solved, interactive, output-only, and explicitly unsuitable problems.\n- Roles: Warmup, Stable, Core, Weakness, Observation, Stretch.\n- Balance strengths, training goals, and ceiling problems; do not fill the set only with weaknesses.\n", min * 100.0, max * 100.0);
    let start = "# Start Here\n\nCreate one personalized static problem set from the supplied candidates and constraints. Return only a valid `com.ojinsight.problem-set` JSON object that follows `PROBLEM-SET.schema.json`. Copy every selected `problem` object from `CANDIDATES.json` without changing it. The result is imported into OJ Insight for review before the user starts a match.\n";
    let state = format!("# Training State\n\nCandidate count: {}\nMode: {mode}\nThe candidate pool was generated by OJ Insight from reliable catalogs and local solved data.\n", candidates.len());
    let schema = r#"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "OJ Insight Problem Set",
  "type": "object",
  "required": ["schema", "schemaVersion", "title", "setType", "tagVisibility", "problems"],
  "properties": {
    "schema": { "const": "com.ojinsight.problem-set" },
    "schemaVersion": { "const": 1 },
    "title": { "type": "string", "minLength": 1 },
    "description": { "type": "string" },
    "setType": { "const": "static" },
    "tagVisibility": { "enum": ["never", "before_solving", "after_ac"] },
    "problems": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["problem", "role"],
        "properties": {
          "role": { "enum": ["Warmup", "Stable", "Core", "Weakness", "Observation", "Stretch"] },
          "note": { "type": "string" },
          "problem": {
            "type": "object",
            "required": ["canonicalId", "platform", "problemKey", "problemId", "name", "url", "difficulty", "tags", "trainingSuitability", "observationDependency", "implementationLoad", "knowledgeDependency", "interactive", "outputOnly"],
            "properties": {
              "canonicalId": { "type": "string", "minLength": 1 },
              "platform": { "enum": ["codeforces", "atcoder", "qoj"] },
              "problemKey": { "type": "string", "minLength": 1 },
              "problemId": { "type": "string" },
              "name": { "type": "string", "minLength": 1 },
              "url": { "type": "string", "minLength": 1 },
              "difficulty": { "type": ["string", "null"] },
              "tags": { "type": "array", "items": { "type": "string" } },
              "trainingSuitability": { "type": ["number", "null"] },
              "observationDependency": { "type": ["number", "null"] },
              "implementationLoad": { "type": ["number", "null"] },
              "knowledgeDependency": { "type": ["number", "null"] },
              "interactive": { "type": "boolean" },
              "outputOnly": { "type": "boolean" }
            }
          }
        }
      }
    }
  }
}"#;
    Ok(TrainingPack { schema: "com.ojinsight.training-pack".into(), schema_version: 2, files: vec![
        TrainingPackFile { name: "START-HERE.md".into(), content: start.into() },
        TrainingPackFile { name: "PROFILE.md".into(), content: profile },
        TrainingPackFile { name: "TRAINING-STATE.md".into(), content: state },
        TrainingPackFile { name: "CONSTRAINTS.md".into(), content: constraints },
        TrainingPackFile { name: "CANDIDATES.json".into(), content: candidates_json },
        TrainingPackFile { name: "PROBLEM-SET.schema.json".into(), content: schema.into() },
    ] })
}

pub(crate) fn training_pack_zip(pack: &TrainingPack) -> Result<Vec<u8>, String> {
    let cursor = Cursor::new(Vec::new());
    let mut writer = zip::ZipWriter::new(cursor);
    let options = zip::write::SimpleFileOptions::default().compression_method(zip::CompressionMethod::Stored);
    for file in &pack.files {
        writer.start_file(&file.name, options).map_err(|e| format!("创建 AI 组题包失败：{e}"))?;
        writer.write_all(file.content.as_bytes()).map_err(|e| format!("写入 AI 组题包失败：{e}"))?;
    }
    writer.finish().map(|cursor| cursor.into_inner()).map_err(|e| format!("完成 AI 组题包失败：{e}"))
}
